STA_IF: int
AP_IF: int


class WLAN:
    def __init__(self, interface_id: int) -> None: ...

    def active(self, state: bool | None = ...) -> bool | None: ...

    def isconnected(self) -> bool: ...

    def connect(self, ssid: str, password: str | None = ...) -> None: ...

    def ifconfig(self) -> tuple[str, str, str, str]: ...
