[project]
name = "anvesha-project-2026-backend"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "pydantic",
    "uvicorn[standard]",
    "supabase",
    "postgrest",
    "python-dotenv",
    "opencv-python-headless",
]

[project.scripts]
app = "backend.api.server:app"
